import React from "react";
import ReactDOM from "react-dom/client";
//import Counter from "./chapter_07/Counter";
//import Counter2 from "./chapter_07/Counter2";
//import Counter3 from "./chapter_08/Counter3";
//import Counter4 from "./chapter_08/Counter4";
import Accommodate from "./chapter_08/Accommodate";
import Timer from "./chapter_08/Timer";
import FetchData from "./chapter_08/FetchData";
const root = document.getElementById("root");
//ReactDOM.createRoot(root).render(<Counter />);
//ReactDOM.createRoot(root).render(<Counter2  />);
//ReactDOM.createRoot(root).render(<Counter3  />);
//ReactDOM.createRoot(root).render(<Counter4  />);
ReactDOM.createRoot(root).render(<Accommodate />);
ReactDOM.createRoot(root).render(<Timer />);
ReactDOM.createRoot(root).render(<FetchData />);